version: '3.8'

services:
  student-survey:
    build: .
    image: suryaprakash737/student-survey:latest
    container_name: student-survey-app
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - survey-network

networks:
  survey-network:
    driver: bridge