apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: student-survey-deployment 
  namespace: student-survey 
spec: 
  replicas: 3 
  selector: 
    matchLabels: 
      app: student-survey 
  template: 
    metadata: 
      labels: 
        app: student-survey 
    spec: 
      containers: 
      - name: student-survey 
        image: suryaprakash737/student-survey:latest 
        ports: 
        - containerPort: 80 
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: student-survey-service 
  namespace: student-survey 
spec: 
  type: NodePort 
  selector: 
    app: student-survey 
  ports: 
    - protocol: TCP 
      port: 80 
      targetPort: 80 
      nodePort: 30080 
