apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-survey-deployment
  labels:
    app: student-survey
spec:
  replicas: 3  # Baseline configuration with 3 pods
  selector:
    matchLabels:
      app: student-survey
  template:
    metadata:
      labels:
        app: student-survey
    spec:
      containers:
      - name: student-survey
        image: suryaprakash737/student-survey:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: student-survey-service
spec:
  type: LoadBalancer
  selector:
    app: student-survey
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Optional: for NodePort access